export const LINES = [
  'Atha samā̍dhipā̱daḥ',
  '1. A̱tha yogānu̍śāsa̱nam',
  '2. Yogaḥ cittavṛtti̍niro̱dhaḥ',
  '3. Ta̱dā dra̱ṣṭuḥ sva̱rū̱pe a̍vasthā̱nam',
  '4. Vṛttisārūpyam i̍tara̱tra',
  '5. Vṛ̱tta̱yaḥ pañcatayyaḥ kli̍ṣṭākli̱ṣṭāḥ',
  '6. Pra̱mā̱ṇa vi̱pa̱ryaya vi̱ka̱lpa ni̱drā smṛ̱taya̍ḥ',
  '7. Pra̱tyakṣa a̱nu̱māna ā̱ga̱māḥ pra̍māṇā̱ni',
  '8. Vi̱pa̱rya̱yo mi̍thyājñā̱nam atadrūpa̍prati̱ṣṭham',
  '9. Śa̱bdajñā̱nā̱nupā̱ti vastuśūnyo̍ vika̱lpaḥ',
  '10. A̱bhā̱vapratyayālambanā tamovṛ̍ttirni̱drā',
  '11. A̱nu̱bhūtaviṣaya a̱saṁpramoṣa̍ḥ smṛ̱tiḥ',
  '12. A̱bhyā̱savai̱rā̱gyā̱bhām ta̍nniro̱dhaḥ',
  '13. Ta̱tra sthi̱tau ya̍tno’bhyā̱saḥ',
  '14. Sa̱ tu dī̱rghakāla nai̱rantarya sa̱tkāra ā̱darā ā̱sevi̱to dṛ̍ḍhabhū̱miḥ',
  '15. Dṛ̱ṣṭānuśravika vi̱ṣa̱yavi̱tṛ̱ṣṇasya va̱śīkārasaṁjñā̍ vairā̱gyam',
  '16. Ta̱tpa̱ram pu̱ru̱ṣakhyā̱teḥ guṇa̍vaitṛ̱ṣṇyam',
  '17. Vi̱ta̱rka vi̱cā̱ra ā̱nanda a̱smi̱tārupa a̱nu̱ga̱māt sa̍ṁprajñā̱taḥ',
  '18. Vi̱rā̱mapratyaya a̱bhyā̱sa pū̱rvaḥ sa̱ṁskāraśe̱ṣaḥ a̱nyaḥ',
  '19. Bha̱vapra̱tya̱yo vi̱dehaprakṛti̍layā̱nām',
  '20. Śra̱ddhā vī̱rya smṛ̱ti sa̱mā̱dhipra̱jñā pūrvaka i̍tare̱ṣām',
  '21. Tīvrasamvegānā̍m āsa̱nnaḥ',
  '22. Mṛ̱du ma̱dhya a̱dhi̱mā̱tra̱tvāt tato’pi̍ viśe̱ṣaḥ',
  '23. Īśvara praṇi̍dhānā̱dvā',
  '24. Kle̱śa ka̱rma vi̱pā̱ka ā̱śa̱yaiḥ a̱pa̱rāmṛṣṭaḥ puruṣaviśeṣa̍ īśva̱raḥ',
  '25. Ta̱tra ni̱ra̱tiśa̱yaṁ sarvajña̍bī̱jam',
  '26. Sa e̱ṣa pū̱rveṣāmapi guruḥ kālenāna̍vacche̱dāt',
  '27. Ta̱sya vā̱cakaḥ pra̱ṇava̍ḥ',
  '28. Tajja̱paḥ tadartha̍ bhāva̱nam',
  '29. Ta̱taḥ pra̱tyakce̱ta̱nā̱dhiga̱maḥ a̱pi antarāyā̍bhava̱śca',
  '30. Vyā̱dhi styā̱na sa̱ṁśaya pra̱mā̱da ā̱lasya a̱vi̱ra̱ti bhrā̱ntidarśana a̱la̱bdhabhū̱mikatva a̱na̱va̱sthi̱ta̱tvāni ci̱ttavi̱kṣe̱pāḥ te a̍ntarā̱yāḥ',
  '31. Du̱ḥkha dau̱rmanasya a̱ṅga̱mejayatva śvā̱sapra̱śvā̱sāḥ vikṣepasa̍habhū̱vaḥ',
  '32. Tat pra̱ti̱ṣe̱dhā̱rtham ekata̍ttvābhyā̱saḥ',
  '33. Mai̱trī ka̱ru̱ṇā mu̱di̱to̱pe̱kṣā̱ṇāṁ su̱kha du̱ḥkha puṇyāpuṇyavi̍ṣayā̱ṇām bhā̱vanātaḥ citta̍prasā̱danam',
  '34. Pra̱cchardana vi̱dhā̱ra̱ṇā̱bhyāṁ vā̍ prāṇā̱syā',
  '35. Vi̱ṣa̱ya̱va̱tī vā pra̱vṛ̱ttiru̱tpa̱nnā ma̱na̱saḥ sthi̍ti ni̱ba̱ndhi̱nī',
  '36. Viśokā vā̍ jyotiṣma̱tī',
  '37. Vītarāgaviṣayaṁ̍ vā ci̱ttam',
  '38. Sva̱pna ni̱drā jñānāla̍ṁbana̱m vā',
  '39. Yathābhimata̍ dhyānā̱dvā',
  '40. Pa̱ra̱māṇu pa̱ra̱mama̱ha̱tvāntaḥ asya va̍śīkā̱raḥ',
  '41. Kṣī̱ṇavṛ̱tteḥ a̱bhijātaseva̍ ma̱ṇeḥ gra̱hī̱tṛ gra̱ha̱ṇa grā̱hyeṣu tatstha tada̱ñjanatā sa̍māpa̱ttiḥ',
  '42. Ta̱tra śa̱bdā̱rthajñā̱navi̱ka̱lpaiḥ sa̱ṁkī̱rṇā sa̱vi̱ta̱rkā sa̱māpa̱ttiḥ',
  '43. Smṛ̱ti̱pa̱ri̱śu̱ddhau sva̱rū̱paśū̱nyeva a̱rthamā̱tra ni̱rbhā̱sa ni̍rvita̱rkā',
  '44. E̱tayaiva sa̱vi̱cā̱ra ni̱rvi̱cā̱ra ca sūkṣmaviṣayā̍ vyākhyā̱ta',
  '45. Sū̱kṣmavi̱ṣa̱ya̱tvaṁ ca aliṅgaparya̍vasā̱nam',
  '46. Tā eva sabīja̍ḥ samā̱dhiḥ',
  '47. Ni̱rvi̱cāra vai̱śā̱ra̱dye adhyātma̍ prasā̱daḥ',
  '48. Ṛ̱ta̱mbha̱rā ta̍tra pra̱jñā',
  '49. Śru̱tā̱numānapra̱jñā̱bhyām a̱nyavi̱ṣa̱yā viśe̍ṣārtha̱tvāt',
  '50. Ta̱jja̱ḥ sa̱ṁskāraḥ anya saṁskāra pra̍tiba̱ndhī',
  // '51. Ta̱syā̱pi ni̱ro̱dhe sa̱rva ni̱ro̱dhāt nirbīja̍ḥ samā̱dhiḥ',
  'Iti pa̱ta̱ñja̱la̱yo̱gasu̱tre samādhi pāda̍ḥ pratha̱maḥ'
]
