export const LINES = [
  'Atha sādha̍napā̱daḥ',
  '1. Ta̱pa̱ḥ svā̱dhyāya īśvaraprāṇidhānānī kri̍yāyo̱gaḥ',
  '2. Sa̱mā̱dhibhā̱vanārthaḥ kle̱śa ta̱nū̱ka̱ra̱ṇā̱rthaśca',
  '3. A̱vi̱dyā a̱smi̱tā rā̱ga dve̱ṣa a̱bhi̱ni̱ve̱śāḥ kle̱śāḥ',
  '4. A̱vi̱dyā kṣe̱tram u̍ttare̱ṣām pra̱su̱pta ta̱nu vi̱cchi̱nna u̍dārā̱ṇām',
  '5. A̱ni̱tya a̱śu̱ci du̱ḥkha a̱nā̱tmasu ni̱tya śu̱ci su̱kha ātmakhyāti̍ḥ a̱vi̱dyā',
  '6. Dṛ̱kda̱rśana śa̱ktyoḥ e̱kā̱tmatā iva a̍smi̱tā',
  '7. Su̱khā̱nuśa̱yī rāgaḥ',
  '8. Du̱ḥkhā̱nuśa̱yī dveṣaḥ',
  '9. Sva̱ra̱savā̱hi vi̱du̱so’pi sa̱mā̱rūḍhaḥ a̱bhi̱ni̱veśaḥ',
  '10. Te pra̱tipra̱sa̱vahe̱yāḥ sū̱kṣmāḥ',
  '11. Dhyā̱nahe̱yāḥ tadvṛttayaḥ',
  '12. Kle̱śamū̱laḥ ka̱rmā̱śa̱yo dṛ̱ṣṭādṛṣṭajanma ve̍danī̱yaḥ',
  '13. Sa̍timū̱le ta̍dvipā̱ko jātyā̍yurbho̱gāḥ',
  '14. Te hlā̱dapa̱ri̱tāpa̍pha̱lāḥ puṇyāpuṇyahe̍tu̱tvāt',
  '15. Pa̱ri̱ṇāma tāpa sa̱ṁskāra̍du̱hkhaiḥ gu̱ṇavṛ̱ttivi̱ro̱dhācca du̱ḥkhameva sarva̍m vive̱kinaḥ',
  '16. He̱yam du̱ḥkham a̍nāga̱tam',
  '17. Dra̱ṣṭṛdṛ̱śya̱yoḥ sa̱ṁyo̱go he̍yahe̱tuḥ',
  '18. Pra̱kā̱śakri̱yāsthi̍tiśī̱lam bhū̱tendriyātma̱kaṁ bho̱gāpavargā̱rthaṁ dṛ̱śyam',
  '19. Vi̱śe̱ṣāviśeṣa li̱ṅga̱mā̱trāliṅgāni guṇa̍parvā̱ṇi',
  '20. Dra̱ṣṭā dṛ̍śimā̱traḥ śu̱ddho’pi pra̱tyayā̍nupa̱śyaḥ',
  '21. Ta̱da̱rtha e̱va dṛ̍śyasya ā̱tmā',
  '22. Kṛ̱tā̱rtham pra̍tina̱ṣṭam api a̱na̱ṣṭam tadanyasādhā̍raṇa̱tvāt',
  '23. Svasvā̱miśa̱ktyoḥ sva̱rū̱popalabdhihetuḥ sa̱ṁyogaḥ',
  '24. Ta̱sya hetu̍ḥ a̱vi̱dyā',
  '25. Ta̱da̱bhā̱vāt sa̱ṁyo̱gābhā̱vo hā̱naṁ taddṛśe̎ḥ kaiva̱lyam',
  '26. Vi̱ve̱kakhyātiḥ a̱vi̱pla̱vā hā̍nopā̱yaḥ',
  '27. Ta̱sya sa̱pta̱dhā prāntabhūmi̍ḥ pra̱jña',
  '28. Yogāṅgānu̍ṣṭhā̱nāt a̱śu̱ddhikṣa̱ye jñā̱nadī̱ptiḥ āvikeka̍khyā̱teḥ',
  '29. Ya̱ma ni̱ya̱ma ā̱sana prā̱ṇāyāma pra̱tyā̱hāra dhā̱ra̱ṇā dhyā̱na sa̱mā̱dhayaḥ aṣṭa̍u aṅgā̱ni',
  '30. A̱hi̱msā sa̱tya a̱ste̱ya bra̱hma̱carya a̱pa̱ri̱gra̱hāḥ ya̱māḥ',
  '31. Jā̱ti de̱śa kā̱la sa̱ma̱ya a̱na̱va̱cchi̱nnāḥ sa̱rvabha̱umāḥ ma̍hāvra̱tam',
  '32. Śa̱uca sa̱ṁtoṣa tapaḥ svā̱dhyāya īśvarapraṇidhānāni̍ niya̱māḥ',
  '33. Vi̱ta̱rkabā̱dha̱ne pratipakṣa̍bhāva̱nam',
  '34. Vi̱ta̱rkāḥ hi̱ṁsādayaḥ kṛ̱ta kā̱ri̱tā a̱nu̱mo̱di̱tāḥ lo̱bha kro̱dha mo̱hapū̱rva̱kāḥ mṛ̱du ma̱dhya a̱dhi̱mā̱trāḥ du̱ḥkha a̱jñā̱na a̱na̱ntapha̱lāḥ iti pra̱tipakṣa̍bhāva̱nam',
  '35. A̱hi̱msāpra̍tiṣṭhā̱yām tatsa̱nni̱dhau vai̍ratyā̱gaḥ',
  '36. Sa̱tyapra̍tiṣṭhā̱yām kri̱̱yāphala ā̍̍śraya̱̱tvam',
  '37. A̱ste̱yapra̍tiṣṭhā̱yām sarvaratna u̍pasthā̱nam',
  '38. Bra̱hma̱ca̱ryapra̍tiṣṭhā̱yām vī̍ryalā̱bhaḥ',
  '39. A̱pa̱ri̱gra̱ha̱stha̱irye ja̱nmaka̱tha̱ṁtā sambodhaḥ',
  '40. Śa̱ucāt svā̱ṅgaju̱gu̱psā pa̱raira̍saṁsargaḥ',
  '41. Sa̱ttvaśu̱ddhi sa̱umanasya a̱ikāgraya i̱ndriyajaya ā̱tmadarśana yogya̍tvāni̱ ca',
  '42. Sa̱nto̱ṣāt anuttamaḥ su̍khalā̱bhaḥ',
  '43. Kā̱yendriyasiddhiḥ a̱śu̱ddhikṣa̱yāt tapasaḥ',
  '44. Svā̱dhyā̱yāt i̱ṣṭade̱va̱tāsaṁprayogaḥ',
  '45. ​​Sa̱mā̱dhisi̱ddhiḥ īśvarapra̍ṇidhā̱nāt',
  '46. Sthirasukha̍māsa̱nam',
  '47. Pra̱ya̱tnaśaithilya anantasa̍māpa̱tti̱bhyām',
  '48. Tato dva̱ndāna̍bhigha̱taḥ',
  '49. Ta̱sminsati śvā̱sapra̱śvā̱sa̱yoḥ ga̱ti̱vi̱cchedaḥ prā̍ṇāyā̱maḥ',
  '50. Bā̱hya ā̱bhyāntara sta̱mbhavṛ̱ttiḥ de̱śa kā̱la sa̱ṁkhyābhiḥ pa̱ri̱dṛ̱ṣṭo dī̍rghasū̱kṣmaḥ',
  '51. Bā̱hya ā̱bhyāntara vi̱ṣa̱yā̱kṣe̱pī caturthaḥ',
  '52. Tataḥ kṣī̱ya̱te prakāśā̍vara̱ṇam',
  '53. Dhā̱ra̱ṇāsu ca yogyatā̍ mana̱saḥ',
  '54. Svavi̱ṣa̱ya a̱sa̱ṁprayo̱ge ci̱tta̱sya sva̱rūpanukāra̍ i̱va i̱ndri̱yāṇām pra̍tyāhā̱raḥ',
  '55. Ta̱taḥ pa̱ra̱māvaśyatā i̍ndriyā̱ṇām',
  'Iti pā̱ta̱ñja̱la̱yo̱gasu̱tre sādhana pāda̍ḥ dvī̱ti̱yaḥ'
]
