export const LINES = [
  "Atha Vibhū̍ti Pā̲daḥ",
  "1. De̱śabandhaḥ cittasya̍ dhāra̱ṇā",
  "2. Ta̱tra pratyayaikatāna̍tā dhyā̱nam",
  "3. Ta̱de̱va a̱rthamā̱trani̱rbhā̱sam sva̱rūpa śūnyamiva̍ samā̱dhiḥ",
  "4. Trayamekatra̍ saṁya̱maḥ",
  "5. Tajja̱yāt pra̍jñālo̱kaḥ",
  "6. Tasya bhūmi̍ṣu vi̱ni̱yogaḥ",
  "7. Tra̱yamantaraṅga̍m pūrve̱bhyaḥ",
  "8. Ta̱da̱piba̱hi̱ra̱ṅgam ni̍rbīja̱sya",
  "9. Vyu̱tthānani̱ro̱dhasa̱ṁskāra̱yoḥ a̱bhi̱bha̱vaprā̍durbhā̱vau ni̱ro̱dhakṣaṇaci̱ttānva̱yo nirodhapa̍riṇā̱maḥ",
  "10. Tasya pra̱śāntavāhitā̍ saṁskā̱rāt",
  "11. Sa̱rvārthatai̱kāgra̱ta̱yoḥ kṣa̱yo̱da̱yau ci̱ttasya sa̲mādhipa̍riṇā̱maḥ",
  "12. Ta̱taḥ pu̱naḥ śā̱ntodi̱tau tu̱lyapra̱tya̱yau ci̱ttasya ekāgratāpa̍riṇā̱maḥ",
  "13. E̱tena bhū̱tendriyeṣu dha̱rma la̱kṣa̱ṇa a̱va̱sthā pa̱ri̱ṇā̱māḥ vyā̍khyā̱tāḥ",
  "14. Śā̱nta u̱di̱ta a̱vya̱pa̱deśya dharmānupā̍tī dha̱rmī",
  "15. Kramānyatvaṁ pariṇāmānya̍tve he̱tuḥ",
  "16. Pa̱ri̱ṇā̱ma̱tra̱ya̱sa̱ṁya̱māt atītānāga̍tajñā̱nam",
  "17. Śa̱bdārthapra̱tya̱yā̱nām i̱ta̱reta̱rādhyā̱sāt saṅkaraḥ tatpra̱vi̱bhāgasa̱ṁya̱māt sarvabhūtaru̍tajñā̱nam",
  "18. Sa̱ṁskārasā̱kṣātka̱ra̱ṇāt pūrvajā̍tijñā̱nam",
  "19. Pra̱tyayasya paraci̍ttajñā̱nam",
  "20. Na̱ ca tatsā̱lamba̱naṁ tasyāviṣayī̍bhūta̱tvāt",
  "21. Kā̱yarū̱pasa̱ṁya̱māt tadgrā̱hyaśa̱ktista̱mbhe ca̱kṣuḥ pra̱kā̱śāsa̱ṁprayo̱ge a̍ntardhā̱nam",
  "22. So̱pakra̱maṁ ni̱ru̱pakra̱maṁ ca karma tatsa̱ṁya̱māt a̱pa̱rā̱ntajñā̱naṁ ari̍ṣṭebhyo̱ vā",
  "23. Maitryādi̍ṣu ba̱lā̱ni",
  "24. Baleṣu hastiba̍ladī̱ni",
  "25. Pra̱vṟttyālo̱kanyā̱sāt sūksma vyavahita viprakṛ̍ṣṭajñā̱nam",
  "26. Bhuvanajñānam sūrye̍ samya̱māt",
  "27. Candre tārāvyū̍hajñā̱nam",
  "28. Dhruve tadga̍tijñā̱nam",
  "29. Nābhicakre kāyavyū̍hajñā̱nam",
  "30. Kaṇṭhakūpe kṣutpipāsā̍nivṛ̱ttiḥ",
  "31. Ku̱rmanā̱ḍyām stha̱iryam",
  "32. Mūrdhajyotiṣi siddha̍darśa̱nam",
  "33. Prā̱tibhā̱dvā sa̱rvam",
  "34. Hṛ̱da̱ye ci̍ttasa̱ṁvit",
  "35. Sa̱ttvapu̱ru̱ṣa̱yoḥ a̱tya̱ntāsa̱ṅkīrṇa̱yoḥ pra̱tya̱yāvi̱śe̱ṣo bhogaḥ pa̱rā̱rtha̱tvāt svā̱rthasa̱ṁya̱māt puru̍ṣajñā̱nam",
  "36. Ta̱taḥ prā̱tibha śrā̱vaṇa ve̱dana ā̱darśa āsvādavārtā̍ jāya̱nte",
  "37. Te sa̱mā̱dhāvu̍pasa̱rgāḥ vyutthāne̍siddhayaḥ",
  "38. Ba̱ndha̱kā̱raṇaśa̱ithi̱lyāt pra̱cā̱rasa̱ṁveda̱nācca ci̱ttasya paraśarī̍rāve̱śaḥ",
  "39. U̱dā̱naja̱yāt ja̱la pa̱ṅka ka̱ṇṭa̱kādiṣu a̱sa̱ṅgaḥ u̍tkrānti̱śca",
  "40. Samānaja̍yāt jva̱la̱nam",
  "41. Śro̱trākā̱śa̱yoḥ sa̱ṁba̱ndhasa̱mya̱māt di̍yyaṁ śro̱tram",
  "42. Kā̱yākā̱śa̱yoḥ sa̱ṁba̱ndhasa̱ṁya̱māt la̱ghutūlasa̱mā̱pa̱tteśca ākā̍śaga̱ma̱nam",
  "43. Ba̱hi̱ra̱ka̱lpi̱tāvṛttiḥ ma̱hā̱vi̱de̱hā tataḥ pra̱kā̱śāvaraṇakṣayaḥ",
  "44. Sthū̱la sva̱rū̱pa sū̱kṣma a̱nvaya a̱rtha̱va̱ttvasa̱ṁya̱māt bhū̍taja̱yaḥ",
  "45. Ta̲to̱’ṇi̱mādiprādurbhāvaḥ kā̱yasa̱ṁpat ta̲ddha̱rmānabhi̍ghāta̱śca",
  "46. Rū̱pa lā̱vaṇya bala va̱jrasa̱ṁha̱na̱na̱tvāni kā̍yasa̱ṁpat",
  "47. Gra̱ha̱ṇa sva̱rū̱pa a̱sm̱itā a̱nvaya a̱rtha̱va̱ttvasa̱mya̱māt indri̍yaja̱yaḥ",
  "48. Ta̱to̱ ma̱no̱ja̱vi̱tvaṁ vikaraṇabhāvaḥ pradhāna̍jaya̱śca",
  "49. Sa̱ttvapu̱ru̱ṣa a̱nya̱tākhyā̱timā̱trasya sa̱rvabhā̱vādhi̱ṣṭhātṛ̱tvaṁ sarvajñā̍tṛtva̱m ca",
  "50. Tadva̱irāgyādapi doṣabījakṣaye̍ kaiva̱lyam",
  "51. Stā̱nyu̱pa̱ni̱ma̱ntra̱ṇe sa̱ṅgasma̱yāka̱ra̱ṇaṁ punaraniṣṭa̍prasa̱ṅgāt",
  "52. Kṣa̱ṇatatkra̱ma̱yoḥ sa̱ṁya̱māt viveka̍jaṁ jñā̱nam",
  "53. Jā̱ti̱la̱kṣaṇade̱śaiḥ a̱nya̱tā a̱na̱va̱cche̱dāt tu̱lya̱yoḥ ta̱taḥ pra̍tipa̱ttiḥ",
  "54. Tā̱ra̱kaṁ sa̱rvavi̱ṣa̱yaṁ sarvathā̍viṣa̱yaṁ a̱kra̱maṁ ceti viveka̍jaṁ jñā̱nam",
  "55. Sa̱ttvapu̱ru̱ṣa̱yoḥ śu̱ddhisāmye̍ kaiva̱lyam",
  "Iti pā̱ta̱ñja̱la̱yo̱gasu̱tre vibhūti pāda̍ḥ tritī̱yaḥ"
]
