export const LINES = [
  "Atha Kaiva̍lyapa̱daḥ",
  "Ja̱nma o̱ṣadhi ma̱ntra ta̱paḥ sa̱mā̱dhi̱jāḥ si̱ddha̍yaḥ",
  "Jā̱tyantarapariṇāmaḥ prakṛt̍āpū̱rāt",
  "Ni̱mi̱tta̱ma̱pra̱yo̱ja̱kaṁ pra̱kṛ̱tī̱nām varaṇabhedastu ta̲taḥ kṣetri̍ka̱vat",
  "Ni̱rmāṇa ci̱ttāṇi asmi̍tā mā̱trāt",
  "Pra̱vṛ̱ttibhe̱de pra̱yoja̱kaṁ cittamekama̍neke̱ṣām",
  "Ta̱tra dhyā̱na̱jam a̍nāśa̱yam",
  "Ka̱rmāśu̱klākṛ̱ṣṇaṁ yoginaḥ trividhami̍tare̱ṣām",
  "Ta̱taḥ tadvi̱pā̱kānugu̱ṇā̱nāmeva a̱bhi̱vyaktiḥ vā̍sanā̱nām",
  "Jā̱ti de̱śa kā̱la vya̱va̱hi̱tā̱nāmapi ā̱nanta̱ryam smṛ̱ti sa̱ṁskāra̱yoḥ eka̍rūpa̱tvāt",
  "Tā̱sam a̱na̱di̱tvaṁ cā’’śiṣo̍ nitya̱tvāt",
  "He̱tu pha̱la ā̱śraya ā̱lamba̱naiḥ sa̱ṅgṛ̱hī̱ta̱tvāt e̱ṣāma̱bhā̱ve ta̍dabhā̱vaḥ",
  "A̱tī̱tānāgataṁ sva̱rū̱pataḥ a̱sti a̱dhvabhedā̍ddharmā̱ṇam",
  "Te vya̱ktasū̱kṣmāḥ gu̍ṇātmā̱naḥ",
  "Pa̱ri̱ṇā̱ma̱ika̱tvāt va̍stuta̱ttvam",
  "Va̱stusā̱mye ci̱ttabhe̱dāt ta̱yorvibha̍ktaḥ pa̱nthāḥ",
  "Na ca̱ikaci̱tta̱ta̱ntraṁ cedvastu tada̱pra̱mā̱ṇa̱kaṁ ta̍dā ki̱ṁ syāt",
  "Tadu̱pa̱rā̱gāpe̱kṣi̱tvāt ci̱tta̱sya va̱stujñā̍tājñā̱tam",
  "Sa̱dājñā̱tāḥ ci̱ttavṛttayaḥ tatpra̱bhoḥ puruṣasya apari̍ṇāmi̱tvāt",
  "Na tatsvābhāsa̍ṁ dṛśya̱tvāt",
  "Ekasamaye ca ubhayānava̍dhāra̱ṇam",
  "Ci̱ttā̱ntaradṛ̱śye bu̱ddhibu̱ddheḥ a̱ti̱prasaṅgaḥ smṛ̱tisa̍ṅkara̱śca",
  "Ci̱teḥ a̱pra̱ti̱sa̱ṅkra̱mā̱yāḥ ta̱dā̱kā̱rāpa̱ttau svabuddhisa̍ṁveda̱nam",
  "Dra̱ṣṭṛdṛ̱śyo̱pa̱ra̱ktaṁ citta̍ṁ sarvā̱rtham",
  "Ta̱da̱sa̱ṁkhyeyavā̱sanābhiḥ ci̱tra̱ma̱pi pa̱rā̱rthaṁ saṁhatya̍kāri̱tvāt",
  "Vi̱śe̱ṣadarśinaḥ ātmabhāvabhāvanā̍ nivṛ̱ttiḥ",
  "Ta̱dā vi̱ve̱kani̱mnaṁ kaivalyaprāgbhā̍raṁ ci̱ttam",
  "Tacchi̱dreṣu pratyayāntarāṇi sa̍ṁskāre̱bhyaḥ",
  "Hā̱name̱ṣāṁ kleśa̍vadu̱ktam",
  "Pra̱sa̱ṅkhā̱ne’pyakusīdasya sa̱rva̱thā vi̱ve̱kakhyā̱teḥ dharmamegha̍ḥ samā̱dhiḥ",
  "Ta̱taḥ kleśakarma̍nivṛ̱ttiḥ",
  "Ta̱dā sarvāvaraṇama̱lā̱petasya jñā̱nasya ā̱na̱ntyāt jñe̍yama̱lpam",
  "Ta̱taḥ kṛ̱tā̱rthā̱nāṁ pariṇāmakramasamāpti̍rguṇā̱nām",
  "Kṣa̱ṇapra̱ti̱yo̱gī pa̱ri̱ṇā̱māparānta nirgrā̍hyaḥ kra̱maḥ",
  "Pu̲ru̱ṣārthaśū̱nyā̱nāṁ gu̱ṇā̱nāṁ pratiprasavaḥ kai̱va̱lyaṁ sva̱rū̱papra̱ti̱ṣṭhā̱ vā ci̱tiśa̍ktiri̱ti",
  "Iti pā̱ta̱ñja̱la̱yo̱gasū̱tre kaivalyapada̍ḥ catu̱rthaḥ"
]
